version: '3'
services:
  servicio-api-calculadora:
    image: ${DOCKER_REGISTRY-}imagen-api-calculadora:v1
    container_name: contenedor-api-calculadora-server
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: aplicacion_api/dockerfile

  servicio-api-calculadora-tests:
    image: ${DOCKER_REGISTRY-}imagen-api-calculadora:v1
    container_name: contenedor-api-calculadora-tests
    command: |
      bash -c "
      pytest unit/ --cov --cov-report=xml:resultados/cobertura/pruebas_unitarias.xml --cov-report=html:resultados/cobertura/pruebas_unitarias --junit-xml=resultados/junit/pruebas_unitarias_junit.xml &&
      junit2html resultados/junit/pruebas_unitarias_junit.xml resultados/junit/pruebas_unitarias_junit.html &&
      pytest rest/ --cov --cov-report=xml:resultados/cobertura/pruebas_rest.xml --cov-report=html:resultados/cobertura/pruebas_rest --junit-xml=resultados/junit/pruebas_rest_junit.xml &&
      junit2html resultados/junit/pruebas_rest_junit.xml resultados/junit/pruebas_rest_junit.html
      "
    volumes:
      - ./resultados_tests/cobertura:/src/resultados/cobertura
      - ./resultados_tests/junit:/src/resultados/junit
    build:
      context: .
      dockerfile: aplicacion_api/dockerfile

  servicio-web-calculadora:
    image: ${DOCKER_REGISTRY-}imagen-web-calculadora:v1
    container_name: contenedor-web-calculadora
    ports:
      - "8081:80"
    build:
      context: .
      dockerfile: aplicacion_web/dockerfile

  servicio-cypress:
    image: cypress/included:4.9.0
    container_name: contenedor-cypress
    depends_on:
      - servicio-web-calculadora
    working_dir: /e2e
    volumes:
      - ./pruebas_e2e/cypress:/e2e/cypress
      - ./pruebas_e2e/cypress.json:/e2e/cypress.json
      - ./resultados_tests/videos:/e2e/cypress/resultados/videos
      - ./resultados_tests/screenshots:/e2e/cypress/resultados/screenshots
      - ./resultados_tests/junit:/e2e/cypress/resultados/junit
    command: cypress run --reporter junit --reporter-options "mochaFile=/e2e/cypress/resultados/junit/pruebas_cypress_junit.xml"