version: '3'
services:
  servicio-api-calculadora:
    image: ${DOCKER_REGISTRY-}imagen-api-calculadora:v1
    container_name: contenedor-api-calculadora-server
    ports:
      - "5000:5000"
    volumes:
      - ./resultados_tests/cobertura:/src/resultados/cobertura
      - ./resultados_tests/junit:/src/resultados/junit
    build:
      context: .
      dockerfile: aplicacion_api/dockerfile

  servicio-web-calculadora:
    image: ${DOCKER_REGISTRY-}imagen-web-calculadora:v1
    container_name: contenedor-web-calculadora
    ports:
      - "8081:80"
    build:
      context: .
      dockerfile: aplicacion_web/dockerfile

  servicio-cypress:
    image: cypress/included:4.9.0
    container_name: contenedor-cypress
    depends_on:
      - servicio-web-calculadora
    working_dir: /e2e
    volumes:
      - ./pruebas_e2e/cypress:/e2e/cypress
      - ./pruebas_e2e/cypress.json:/e2e/cypress.json
      - ./resultados_tests/videos:/e2e/cypress/resultados/videos
      - ./resultados_tests/screenshots:/e2e/cypress/resultados/screenshots
      - ./resultados_tests/junit:/e2e/cypress/resultados/junit